###
GET https://pokeapi.co/api/v2/pokemon/pikachufa

###
GET http://localhost:62449/api/CadastroPokemonApi/Listar

###
GET http://localhost:62449/api/CadastroPokemonApi/LocalizarPorNome/Carol

###
DELETE  http://localhost:62449/api/CadastroPokemonApi/Deletar/2016

###
POST http://localhost:62449/api/CadastroPokemonApi/Cadastrar
Content-Type: application/json

{
    "nome" : "paulo marreta",
    "email" : "marretao@pedreiro.com",
    "idade" : 65,
    "nomepokemonpreferido" : "larvitar",
    "numeropokemon" : 666,
    "urlfotopokemon" : "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png"
}

###
PUT http://localhost:62449/api/CadastroPokemonApi/editar/2014
Content-Type: application/json

{
    "nome" : "Carllos Vendetta",
    "email" : "Vendeta@vinganca.com.br",
    "idade" : 17,
    "nomepokemonpreferido" : "larvitar",
    "numeropokemon" : 246,
    "urlfotopokemon" : "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/246.png"
}


